version: '3.8'

services:
  aio-core:
    image: kmaisanquantum/deeps-systems-aio-core:latest
    container_name: aio-core-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - GITHUB_API_BASE_URL=${GITHUB_API_BASE_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - VULTR_API_BASE_URL=${VULTR_API_BASE_URL}
      - VULTR_API_KEY=${VULTR_API_KEY}
      - HOSTGATOR_API_BASE_URL=${HOSTGATOR_API_BASE_URL}
      - HOSTGATOR_API_KEY=${HOSTGATOR_API_KEY}
    restart: always
